pronoun_user_field_name:
  type: string
  default: "Pronomes"

pronoun_border_color:
  type: string
  default: "#e91e63"

pronoun_text_color:
  type: string
  default: "#ffffff"

pronoun_background_color:
  type: string
  default: "transparent"
